# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mkuehl <mkuehl@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/17 14:16:14 by mkuehl            #+#    #+#              #
#    Updated: 2022/01/25 21:15:14 by mkuehl           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

HEADER = libft.h

CC = gcc

CFLAGS = -Wall -Wextra -Werror

SRCS = ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_strcmp.c\
	ft_isprint.c ft_itoa.c ft_memccpy.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c\
	ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_split.c ft_strchr.c get_next_line.c\
	ft_strdup.c ft_strjoin.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strmapi.c ft_strncmp.c ft_isnumber.c\
	ft_strnstr.c ft_strrchr.c ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c get_next_line_utils.c\


OBJS := $(SRCS:.c=.o)

.PHONY: all clean fclean re

all:	$(NAME)

%.o: %.c $(HEADER)
	@$(CC) -c $(CFLAGS) -I $(HEADER) $< -o $@

$(NAME): $(OBJS)
	@ar rcs $(NAME) $?

clean:
	@rm -rf $(OBJS)

fclean:	clean
	@rm -rf $(NAME)

re:	fclean all